Update to mocha 5.1
Note that jsdom 11.6 and above result in:
Error: Uncaught [TypeError: Cannot read property 'responseStart' of undefined]
    at reportException (/Users/dem/projects/load-web-page-jsdom-mocha/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
...
at /Users/dem/projects/load-web-page-jsdom-mocha/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:93:12